adding linux-misc as submodule and other issues

diff --git a/badipskeymgt b/badipskeymgt
--- a/badipskeymgt
+++ b/badipskeymgt
@@ -14,69 +14,26 @@
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 _srcsbinpath=$(dirname $(readlink -f $0))
+
+declare -a _requiredfiles
+declare -a _requiredexefiles
+
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
+		exit 1
+	fi
+fi
+
 _badipskey=""
 _badipscomkeyprefix=".key-badsipcom-"
 _myhostip="$(ip route get 1 | awk '{print $NF;exit}')"
 _badipskeyfile="${_badipscomkeyprefix}${_myhostip//./-}"
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
-		exit 1
-	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
-
-function trimStr(){
-	local _deli _deli2 _strtotrim
-	if [ "$#" -eq 0 ] ; then
-		return 1
-	elif [ "$#" -eq 1 ] ; then
-		_deli=" "
-		_deli2=" "
-		_strtotrim="$*"
-	elif [ "$#" -eq 2 ] ; then
-		_deli="$1"
-		_deli2="$1"
-		shift
-		_strtotrim="$*"
-	elif [ "$#" -gt 2 ] ; then
-		_deli="$1"
-		shift
-		_deli2="$1"
-		shift
-		_strtotrim="$*"
-	fi
-	_strtotrim="${_strtotrim/#$_deli}"
-	_strtotrim="${_strtotrim/%$_deli2}"
-	echo "$_strtotrim"
-}
 
 if [ -f "$_badipskeyfile" ] ; then
 	_badipskey=$(cat "$_badipskeyfile")
diff --git a/cleanips b/cleanips
--- a/cleanips
+++ b/cleanips
@@ -14,6 +14,25 @@
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 _srcsbinpath=$(dirname $(readlink -f $0))
+
+declare -a _requiredfiles
+declare -a _requiredexefiles
+
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
+		exit 1
+	fi
+fi
+
+if [ ! -d "$_srcsbinpath/.store" ] ; then
+	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/installme first." 1>&2
+	exit 1
+fi
 _noask=""
 if [ "$1" = "noask" ] ; then
 	_noask="noask"
@@ -30,63 +49,6 @@ _dbfile="$1"
 #shift
 #_manualblocklist="$1"
 
-
-
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
-		exit 1
-	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
-
-function isvalidip4(){
-	if echo "$1" | grep -qE "^(([0-9][0-9]?|[0-1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])\.){3}([0-9][0-9]?|[0-1][0-9][0-9]|[2][0-4][0-9]|[2][5][0-5])$" ; then
-		return 0
-	fi
-	return 1
-}
-
-function isposint(){
-	local _val
-	_val=$1
-	if [ -n "$_val" ] && echo "$_val" | grep -q "^-\?[0-9]*$" && [ "$_val" -ge 0 ] ; then
-	return 0
-	fi
-	return 1
-}
-
-function strtoarry(){
-	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
-	eval unset $_retarray
-	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
-}
 
 if [ -z "$_dbfile" ] || [ ! -f "$_dbfile" ] ; then
 	
@@ -146,28 +108,6 @@ if [ -z "$_maxtopermanent" ] || ! isposint "$_maxtopermanent" ; then
 	fi
 fi
 
-
-
-#if [ -z "$_manualblocklist" ] || [ ! -f "$_manualblocklist" ] ; then
-	
-	#if [ -z  "$_noask" ] ; then
-		#if [ -f "$_srcsbinpath/manualblocked.list" ] && confirmtogo "We found a manually listed block ips file at $_srcsbinpath/manualblocked.list, do you want to use this list? (yes/press enter only to cancel): " ; then
-			#_manualblocklist="$_srcsbinpath/manualblocked.list"
-		#fi
-		
-		#if [ -z "$_manualblocklist" ] && confirmtogo "do you want to use a manual list of blocked ips?(yes/press enter only to cancel): " ; then
-			#read -p "Please enter the location of manual list of blocked ips file: " _manualblocklist
-			#if [ -z "$_manualblocklist" ] || [ ! -f "$_manualblocklist" ] ; then
-				#echo "ERROR: Your input: $_manualblocklist is not a valid file, file doesn't exist." 1>&2
-				#exit 1
-			#fi
-		#fi
-	#else
-		#if [ -f "$_srcsbinpath/manualblocked.list" ] ; then
-			#_manualblocklist="$_srcsbinpath/manualblocked.list"
-		#fi
-	#fi
-#fi
 
 
 ufwunban(){
diff --git a/installme b/installme
--- a/installme
+++ b/installme
@@ -15,141 +15,61 @@
 
 _srcsbinpath=$(dirname $(readlink -f $0))
 
-function getosname(){
-	if [ -f /etc/os-release ] ; then
-		eval $(cat /etc/os-release | grep "ID")
-		echo $ID
-	fi
-}
+declare -a _requiredfiles
+declare -a _requiredexefiles
 
-function confirmtogo(){
-	local _conit _valtogo _msg
-	_msg=$1
-	_valtogo=$2
-	if [ -z "$_msg" ] ; then
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+_requiredexefiles[${#_requiredexefiles[@]}]="getgitrepo"
+_requiredexefiles[${#_requiredexefiles[@]}]="githublatest"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
 		exit 1
 	fi
-	read -p "$_msg" _conit
-	_conit=${_conit,,}
-	if [ -z "$_valtogo" ] ; then
-		_valtogo="yes"
-	else
-		_valtogo=${_valtogo,,}
-	fi
-	if [ "$_valtogo" = "notempty" ] ; then
-		if [ ! -z "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ "$_valtogo" = "pathexist" ] ; then
-		if [ -e "$_conit" ] ; then
-			echo "$_conit"
-			return 0
-		else
-			return 1
-		fi
-	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
-		return 0
-	fi
-	return 1
-}
+fi
 
-function escapepath(){
-	local _thep
-	_thep=$1
-	_thep=${_thep//\//\\/}
-	echo "$_thep"
-}
-
-function replaceline(){
-	local _pattern _replace _file
-	_pattern=$1
-	_replace=$2
-	_file=$3
-	sed -e "/$_pattern/ { c \
-	$_replace
-	}" "$_file"
-}
-
-_miscpath=""
-function addmiscpath(){
-	local _var _com _comloc
-	_com=$1
-	_var="_${1}"
-	_comloc=$2
-	if [ -z "$_comloc" ] || [ ! -x "$_comloc" ]; then 
-		_comloc=$(command -v "$_com")
-	fi
-	if [ -z "$_comloc" ] ; then
-		echo "	ERROR: linux-misc/$_com command not found in your system. Please install it from https://github.com/helal00/linux-misc before continue. If the command is already installed, plese specify it in $_miscpath with adding a line as '$_var=/path/to/$_com'. Create the file if doesn't exist already."
-		return 1
-	else		
-		if ! grep -Fq "$_var=" "$_miscpath" ; then
-			sed -i -e '$a\' "$_miscpath"
-			echo "$_var=$_comloc" >> "$_miscpath"
-		fi
-		echo "$_comloc"
-	fi
-	return 0
-}
-
- 
 _installerdir="$PWD/installer_dir"
 _curdir=$PWD
 _osname=$(getosname)
 _debianbased=1
-if [ "$_osname" = "debian" ] || [ "$_osname" = "ubuntu" ] ; then
-	_debianbased=0
-	sudo apt-get -y install ufw python curl jq bc whois
-	if [ $? -ne 0 ] ; then
-		echo "'ufw python curl jq bc whois whois' packages can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+
+if ! isinstalled "ufw" && isinstalled "python" && isinstalled "curl" && isinstalled "jq" && isinstalled "bc" ; then
+	if [ "$_osname" = "debian" ] || [ "$_osname" = "ubuntu" ] ; then
+		_debianbased=0
+		sudo apt-get -y install ufw python curl jq bc whois
+		if [ $? -ne 0 ] ; then
+			echo "'ufw python curl jq bc whois whois' packages can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+			exit 1
+		fi
+	else
+		
+		echo "	WARNING: Your operating system is not officially supported for automated installation, 'ufw python curl jq bc' packages need to be installed by yourself. Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. Please install 'ufw python curl jq bc' packages for your distro to use this utility. e.g. for debian/ubuntu, sudo apt-get -y install ufw python curl jq bc" 1>&2
 		exit 1
 	fi
-else
-	echo "	WARNING: Your operating system is not officially supported for automated installation, 'ufw python curl jq bc' packages need to be installed by yourself. Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. Please install 'ufw python curl jq bc' packages for your distro to use this utility. e.g. for debian/ubuntu, sudo apt-get -y install ufw python curl jq bc" 1>&2
-	exit 1
 fi
-
 
 if sudo ufw status | grep -q inactive ; then
 	sudo ufw limit ssh
 	ufw enable
-	echo "Only the ssh port (see /etc/services for port definations) is open. You should open other ports using 'sudo ufw' command for the applications you are using. e.g. sudo ufw http https" 1>&2
+	echo "Only the ssh port (see /etc/services for port definations) is open. You should open other ports using 'sudo ufw' command for the applications you are using. e.g. 'sudo ufw allow http/tcp' or 'sudo ufw allow https/tcp'" 1>&2
 fi
 ufw status
 
 mkdir -p $_installerdir
 cd $_installerdir
-$_srcsbinpath/getgitrepo https://github.com/seb-m/pyinotify last
+$_getgitrepo https://github.com/seb-m/pyinotify last
 cd pyinotify-*
 python setup.py install
 python -m pyinotify -h
 cd $_curdir
-sudo mkdir -p $_srcsbinpath/.store
-
-if [ ! -z "$_srcsbinpath" ]; then
-	
-	_miscpath="$_srcsbinpath/.store/linux-misc"
-	if [ -s "$_miscpath" ] ; then
-		. "$_miscpath"
-	fi
-	
-	if ! _calloutput=$(addmiscpath "getgitrepo" "$_getgitrepo") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
-	else
-		_getgitrepo="$_calloutput"
-	fi
-
-	if ! _calloutput=$(addmiscpath "githublatest" "$_githublatest") ; then
-		echo "$_calloutput" 1>&2
-		exit 1
-	else
-		_githublatest="$_calloutput"
-	fi
-
+_storeexist=1
+if [ -d "$_srcsbinpath/.store" ] ; then
+	_storeexist=0
+else
+	sudo mkdir -p "$_srcsbinpath/.store"
 fi
 
 _f2blocation=$(command -v fail2ban-client)
@@ -157,28 +77,36 @@ _f2blocation=$(command -v fail2ban-client)
 if [ ! -z "$_f2blocation" ] ; then
 	fail2ban-client reload
 	_insatlledver=$("$_f2blocation" version)
-	_latestversion=$($_srcsbinpath/githublatest https://github.com/fail2ban/fail2ban)
+	_latestversion=$($_githublatest https://github.com/fail2ban/fail2ban)
 	if [ "$_insatlledver" != "$_latestversion" ] ; then
 		echo "	INFORMATION: Newer version of fail2ban avaibale. You have version: $_insatlledver and version  available: $_latestversion. Check https://github.com/fail2ban/fail2ban for more detials, if you wish to upgrade fail2ban."
 	fi
 else
 	_installanyway=1
 	if [ "$_debianbased" -eq 1 ] && [ -z "$_f2blocation" ] ; then
-		echo "	IMPORTANT: Your operating system is not officially supported for automated installation.Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. we can't fin Fail2ban installed in your system." 1>&2
+		echo "	IMPORTANT: Your operating system is not officially supported for automated installation.Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. we can't find Fail2ban installed in your system." 1>&2
 		if confirmtogo "Do you want to install Fail2ban yourself or want us to fetch latest version from github and do the basic setup? In later case, you might need to copy some init scripts to your distro's init directories to start fail2ban automatically on reboot. If you know how to do that, you should let us fetach the latest version from github. Please type 'yes ' to fetch fail2ban latest or press only enter to quit this script.(yes/enter to quit): " ; then
 			_installanyway=0
+		else
+			if [ "$_storeexist" -eq 1 ] ; then
+				sudo rm -rf "$_srcsbinpath/.store"
+			fi
+			exit 1
 		fi
 	fi
 
 	if ( [ "$_debianbased" -eq 0 ] || [ "$_installanyway" -eq 0 ] ) && [ -z "$_f2blocation" ] ; then
 		
 		cd $_installerdir
-		$_srcsbinpath/getgitrepo https://github.com/fail2ban/fail2ban last
+		$_getgitrepo last https://github.com/fail2ban/fail2ban
 		cd fail2ban-*
 		python setup.py install
 		_f2blocation=$(command -v fail2ban-client)
 		if [ -z "$_f2blocation" ] ; then 
 			echo "fail2ban can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+			if [ "$_storeexist" -eq 1 ] ; then
+				sudo rm -rf "$_srcsbinpath/.store"
+			fi
 			exit 1
 		fi
 		if [ -d /etc/logrotate.d/ ] ; then
diff --git a/ufwcustom b/ufwcustom
--- a/ufwcustom
+++ b/ufwcustom
@@ -38,6 +38,25 @@ _app="${20}"
 _port="${21}"
 _protocol="${22}"
 
+declare -a _requiredfiles
+declare -a _requiredexefiles
+
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
+		exit 1
+	fi
+fi
+
+if [ ! -d "$_srcsbinpath/.store" ] ; then
+	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/installme first." 1>&2
+	exit 1
+fi
+
 
 #echo "I am running.......no worries..." > "$_srcsbinpath/testip.log"
 
@@ -51,58 +70,6 @@ if [ "$_isignoreip" -eq 1 ] && [ -f "$_srcsbinpath/iptoignore" ] ; then
 		exit 0
 	fi
 fi
-
-function strtoarry(){
-	local _str _retarray _deli _c _l;_str=$1 _retarray=$2 _deli=$3
-	eval unset $_retarray
-	_c=-1;while read -r _l; do _c=$((_c+1));eval $_retarray[$_c]='$_l';done <<< "$(echo $_str | sed -e "s/$_deli/\n/g")"
-}
-
-function isposint(){
-	local _val
-	_val=$1
-	if [ -n "$_val" ] && echo "$_val" | grep -q "^-\?[0-9]*$" && [ "$_val" -ge 0 ] ; then
-		return 0
-	fi
-	return 1
-}
-
-function replaceline(){
-	local _pattern _replace _file
-	_pattern=$1
-	_replace=$2
-	_file=$3
-	sed -i "/$_pattern/ { c \
-	$_replace
-	}" "$_file"
-}
-
-function join { local IFS="$1"; shift; echo "$*"; }
-
-function trimStr(){
-	local _deli _deli2 _strtotrim
-	if [ "$#" -eq 0 ] ; then
-		return 1
-	elif [ "$#" -eq 1 ] ; then
-		_deli=" "
-		_deli2=" "
-		_strtotrim="$*"
-	elif [ "$#" -eq 2 ] ; then
-		_deli="$1"
-		_deli2="$1"
-		shift
-		_strtotrim="$*"
-	elif [ "$#" -gt 2 ] ; then
-		_deli="$1"
-		shift
-		_deli2="$1"
-		shift
-		_strtotrim="$*"
-	fi
-	_strtotrim="${_strtotrim/#$_deli}"
-	_strtotrim="${_strtotrim/%$_deli2}"
-	echo "$_strtotrim"
-}
 
 function fetchBadips(){
 	local _filestore _tempfilestore _dbname _cat _score _interval _key _response
diff --git a/unbanip b/unbanip
--- a/unbanip
+++ b/unbanip
@@ -14,19 +14,30 @@
 #along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 _srcsbinpath=$(dirname $(readlink -f $0))
+
+declare -a _requiredfiles
+declare -a _requiredexefiles
+
+_requiredfiles[${#_requiredfiles[@]}]="functions"
+
+if [ ! -z "$_srcsbinpath" ] ; then
+	if [ -s "$_srcsbinpath/resolve" ] ; then
+		. $_srcsbinpath/resolve	
+	else
+		echo "$_srcsbinpath/resolve file not found!" 1>&2
+		exit 1
+	fi
+fi
+
+if [ ! -d "$_srcsbinpath/.store" ] ; then
+	echo "The prgram is not yet ready to run. Please run $_srcsbinpath/installme first." 1>&2
+	exit 1
+fi
 _delete=""
 _counter=0
 _curcounter=0
 _ip=$1
 
-function isint(){
-	local _val
-	_val=$1
-	if [ -n "$_val" ] && echo "$_val" | grep -q "^-\?[0-9]*$" ; then
-		return 0
-	fi
-	return 1
-}
 
 if [ -z "$_ip" ] ; then
 	echo "No ip given." 1>&2
