fixing installme

diff --git a/installme b/installme
--- a/installme
+++ b/installme
@@ -35,36 +35,60 @@ _installerdir="$PWD/installer_dir"
 _curdir=$PWD
 _osname=$(getosname)
 _debianbased=1
+_toinstall=""
 
-if ! isinstalled "ufw" && isinstalled "python" && isinstalled "curl" && isinstalled "jq" && isinstalled "bc" ; then
-	if [ "$_osname" = "debian" ] || [ "$_osname" = "ubuntu" ] ; then
-		_debianbased=0
-		sudo apt-get -y install ufw python curl jq bc whois
+if ! isinstalled "ufw" &>>/dev/null ; then
+	_toinstall=" ufw"
+fi
+if ! isinstalled "python" &>>/dev/null ; then
+	_toinstall="${_toinstall} python"
+fi
+if ! isinstalled "curl" &>>/dev/null ; then
+	_toinstall="${_toinstall} curl"
+fi
+if ! isinstalled "jq" &>>/dev/null; then
+	_toinstall="${_toinstall} jq"
+fi
+if ! isinstalled "bc" &>>/dev/null ; then
+	_toinstall="${_toinstall} bc"
+fi
+_toinstall=$(trimStr "$_toinstall")
+_aptgetloc=$(isinstalled "apt-get")
+if [ ! -z "$_aptgetloc" ] ; then
+	_debianbased=0
+fi
+if [ ! -z "$_toinstall" ] ; then
+	if [ "$_debianbased" -ne 0 ] ; then
+		echo "	ERROR: We cannot find 'apt-get' in your operating system for automated installation, '$_toinstall' packages need to be installed by yourself. Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. Please install '$_toinstall' packages for your distro to use this utility. e.g. for debian/ubuntu, sudo apt-get -y install $_toinstall" 1>&2
+		exit 1
+	else
+		sudo apt-get -y install "$_toinstall"
 		if [ $? -ne 0 ] ; then
-			echo "'ufw python curl jq bc whois whois' packages can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+			echo "	ERROR: '$_toinstall' packages can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
 			exit 1
 		fi
-	else
-		
-		echo "	WARNING: Your operating system is not officially supported for automated installation, 'ufw python curl jq bc' packages need to be installed by yourself. Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. Please install 'ufw python curl jq bc' packages for your distro to use this utility. e.g. for debian/ubuntu, sudo apt-get -y install ufw python curl jq bc" 1>&2
-		exit 1
 	fi
 fi
 
 if sudo ufw status | grep -q inactive ; then
 	sudo ufw limit ssh
 	ufw enable
-	echo "Only the ssh port (see /etc/services for port definations) is open. You should open other ports using 'sudo ufw' command for the applications you are using. e.g. 'sudo ufw allow http/tcp' or 'sudo ufw allow https/tcp'" 1>&2
+	echo "	INFORMATION: Only the ssh port (see /etc/services for port definations) is open. You should open other ports using 'sudo ufw' command for the applications you are using. e.g. 'sudo ufw allow http/tcp' or 'sudo ufw allow https/tcp'" 1>&2
 fi
-ufw status
+echo "ufw $(ufw status)"
 
-mkdir -p $_installerdir
-cd $_installerdir
-$_getgitrepo https://github.com/seb-m/pyinotify last
-cd pyinotify-*
-python setup.py install
-python -m pyinotify -h
-cd $_curdir
+if ! python -m pyinotify -h &>>/dev/null ; then
+	echo "into pynotify"
+	exit 0
+	mkdir -p $_installerdir
+	cd $_installerdir
+	$_getgitrepo last https://github.com/seb-m/pyinotify
+	cd pyinotify-*
+	python setup.py install
+	python -m pyinotify -h
+	cd $_curdir
+fi
+
 _storeexist=1
 if [ -d "$_srcsbinpath/.store" ] ; then
 	_storeexist=0
@@ -75,7 +99,23 @@ fi
 _f2blocation=$(command -v fail2ban-client)
 
 if [ ! -z "$_f2blocation" ] ; then
-	fail2ban-client reload
+	if [ $_debianbased -eq 0 ]; then
+		if [ ! -x "/etc/init.d/fail2ban" ] || [ ! -s "/etc/init/fail2ban.conf" ] ; then
+			_f2blocation=""
+		else
+			service fail2ban start
+		fi
+	else
+		fail2ban-client start
+	fi
+	if [ ! -z "$_f2blocation" ] ; then
+		if ! fail2ban-client status &>>/dev/null ; then
+			_f2blocation=""
+		fi
+	fi	
+fi
+
+if [ ! -z "$_f2blocation" ] ; then
 	_insatlledver=$("$_f2blocation" version)
 	_latestversion=$($_githublatest https://github.com/fail2ban/fail2ban)
 	if [ "$_insatlledver" != "$_latestversion" ] ; then
@@ -83,9 +123,9 @@ if [ ! -z "$_f2blocation" ] ; then
 	fi
 else
 	_installanyway=1
-	if [ "$_debianbased" -eq 1 ] && [ -z "$_f2blocation" ] ; then
-		echo "	IMPORTANT: Your operating system is not officially supported for automated installation.Fully supported version is Debian 7 (wheezy) or Ubuntu 14.04 (truesty) or up. we can't find Fail2ban installed in your system." 1>&2
-		if confirmtogo "Do you want to install Fail2ban yourself or want us to fetch latest version from github and do the basic setup? In later case, you might need to copy some init scripts to your distro's init directories to start fail2ban automatically on reboot. If you know how to do that, you should let us fetach the latest version from github. Please type 'yes ' to fetch fail2ban latest or press only enter to quit this script.(yes/enter to quit): " ; then
+	if [ "$_debianbased" -eq 1 ] ; then
+		echo "	IMPORTANT: we can't find Fail2ban installed in your system." 1>&2
+		if confirmtogo "Do you want to install Fail2ban yourself or want us to fetch latest version from github and do the basic setup? In later case, you might need to copy some init scripts to your distro's init directories to start fail2ban automatically on reboot. If you know how to do that, you should let us fetch the latest version from github. Please type 'yes ' to fetch fail2ban latest or press only enter to quit this script.(yes/enter to quit): " ; then
 			_installanyway=0
 		else
 			if [ "$_storeexist" -eq 1 ] ; then
@@ -95,15 +135,14 @@ else
 		fi
 	fi
 
-	if ( [ "$_debianbased" -eq 0 ] || [ "$_installanyway" -eq 0 ] ) && [ -z "$_f2blocation" ] ; then
-		
+	if [ "$_debianbased" -eq 0 ] || [ "$_installanyway" -eq 0 ] ; then
 		cd $_installerdir
 		$_getgitrepo last https://github.com/fail2ban/fail2ban
 		cd fail2ban-*
 		python setup.py install
 		_f2blocation=$(command -v fail2ban-client)
 		if [ -z "$_f2blocation" ] ; then 
-			echo "fail2ban can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+			echo "	ERROR: fail2ban can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
 			if [ "$_storeexist" -eq 1 ] ; then
 				sudo rm -rf "$_srcsbinpath/.store"
 			fi
@@ -136,8 +175,22 @@ else
 			cp files/fail2ban.upstart /etc/init/fail2ban.conf
 			_f2blocationre=${_f2blocation////\\/}
 			sed -i "s/\/usr\/bin\/fail2ban-client/$_f2blocationre/g" /etc/init/fail2ban.conf
+			service fail2ban start
 		else
-			echo "Please copy and rename init/service files from $(eval echo "${_installerdir}/fail2ban-*")/files/ to the appropriate directory for your distro" 1>&2
+			fail2ban-client start
+			echo "	IMPORTANT: Please copy and rename init/service files from $(eval echo "${_installerdir}/fail2ban-*")/files/ to the appropriate directory for your distro" 1>&2
+		fi
+		if [ $_debianbased -eq 0 ]; then
+			service fail2ban start
+		else
+			fail2ban-client start
+		fi
+		if ! fail2ban-client status &>>/dev/null ; then
+			echo "	ERROR: fail2ban can't be installed properly, there is some error. Please install them yourselft to continue." 1>&2
+			if [ "$_storeexist" -eq 1 ] ; then
+				sudo rm -rf "$_srcsbinpath/.store"
+			fi
+			exit 1
 		fi
 		cd $_curdir
 	fi
