separating linux-misc utils

diff --git a/installme b/installme
--- a/installme
+++ b/installme
@@ -36,12 +36,20 @@ function confirmtogo(){
 	else
 		_valtogo=${_valtogo,,}
 	fi
-	if [ "$_valtogo" = "notempty" ] && [ ! -z "$_conit" ] ; then
-		echo "$_conit"
-		return 0
-	elif [ "$_valtogo" = "pathexist" ] && [ -e "$_conit" ] ; then
-		echo "$_conit"
-		return 0
+	if [ "$_valtogo" = "notempty" ] ; then
+		if [ ! -z "$_conit" ] ; then
+			echo "$_conit"
+			return 0
+		else
+			return 1
+		fi
+	elif [ "$_valtogo" = "pathexist" ] ; then
+		if [ -e "$_conit" ] ; then
+			echo "$_conit"
+			return 0
+		else
+			return 1
+		fi
 	elif [ ! -z "$_conit" ] && [ "$_conit" = "$_valtogo" ] ; then
 		return 0
 	fi
@@ -63,6 +71,28 @@ function replaceline(){
 	sed -e "/$_pattern/ { c \
 	$_replace
 	}" "$_file"
+}
+
+_miscpath=""
+function addmiscpath(){
+	local _var _com _comloc
+	_com=$1
+	_var="_${1}"
+	_comloc=$2
+	if [ -z "$_comloc" ] || [ ! -x "$_comloc" ]; then 
+		_comloc=$(command -v "$_com")
+	fi
+	if [ -z "$_comloc" ] ; then
+		echo "	ERROR: linux-misc/$_com command not found in your system. Please install it from https://github.com/helal00/linux-misc before continue. If the command is already installed, plese specify it in $_miscpath with adding a line as '$_var=/path/to/$_com'. Create the file if doesn't exist already."
+		return 1
+	else		
+		if ! grep -Fq "$_var=" "$_miscpath" ; then
+			sed -i -e '$a\' "$_miscpath"
+			echo "$_var=$_comloc" >> "$_miscpath"
+		fi
+		echo "$_comloc"
+	fi
+	return 0
 }
 
  
@@ -97,6 +127,30 @@ cd pyinotify-*
 python setup.py install
 python -m pyinotify -h
 cd $_curdir
+sudo mkdir -p $_srcsbinpath/.store
+
+if [ ! -z "$_srcsbinpath" ]; then
+	
+	_miscpath="$_srcsbinpath/.store/linux-misc"
+	if [ -s "$_miscpath" ] ; then
+		. "$_miscpath"
+	fi
+	
+	if ! _calloutput=$(addmiscpath "getgitrepo" "$_getgitrepo") ; then
+		echo "$_calloutput" 1>&2
+		exit 1
+	else
+		_getgitrepo="$_calloutput"
+	fi
+
+	if ! _calloutput=$(addmiscpath "githublatest" "$_githublatest") ; then
+		echo "$_calloutput" 1>&2
+		exit 1
+	else
+		_githublatest="$_calloutput"
+	fi
+
+fi
 
 _f2blocation=$(command -v fail2ban-client)
 
